### PR TITLE
Uq to main

### PR DESCRIPTION
**Pull request by tcoonsUM**
Implementation of uq code using solver code.

Tasks for completion:

- [x] Samples are generated from priors
- [x] Sample matrices are computed and run thru model
- [x] Sobol' indices are reasonable for mild sample #'s
- [ ] Solver does not produce errors when used in uq code

### CODE REVIEW

**Comment by noylnalyd** [comment]
Hey, I'm trying to review this but I don't want to overwrite data. What files specifically can I run?

**Comment by tcoonsUM** [comment]
> Hey, I'm trying to review this but I don't want to overwrite data. What files specifically can I run?

It's okay if you write over the data, you can run `bash parallelRun.sh  nProcesses nSamples` if you want to see it work. The nProcesses is the number of cores to run on and nSamples is the number of Monte Carlo samples

**Comment by noylnalyd** [comment]
Sweet ok, let me finish timing the runs and then I'll finish the review. The code is really really fast with PBM's Gauss-Seidel at .00006 to solve the matrix on average. Runs take about 4s for the full 3600 timesteps.

**Comment by tcoonsUM** [comment]
> Sweet ok, let me finish timing the runs and then I'll finish the review. The code is really really fast with PBM's Gauss-Seidel at .00006 to solve the matrix on average. Runs take about 4s for the full 3600 timesteps. A far cry from 40 minutes!

That's awesome!! Also, it looks like I sometimes get some instability in your code and the run fails, say once every 400 runs, usually a la `Assertion failed: (!isnan(abs(Rho[eleIdx]))), function rhocp, file Simulator.cpp, line 412`. Do you think tightening up the priors would help, or is this instability expected sometimes? If you run my parallelRun.sh file with say 500 samples I bet you can replicate it if you want to debug (or I can try to do the same thing to see what uq parameters are causing the instability)

**Pull request merged**
